### ISSUE TITLE
[Auth] Allow persistent sessions

### ISSUE THREAD

**Issue by mpekala23** [Ameelio/connect-api-nest#70]
**Is your feature request related to a problem? Please describe.**
Currently there is not a way for the mobile app to function without the user logging in with username / password. This means anytime the user killed the app they would have to log in again.

**Describe the solution you'd like**
An endpoint that allows the user to pass in a token (either their normal token, or a special remember token, both are okay) and returns the User object for the associated user and a valid cookie that can be used in requests.

**Describe alternatives you've considered**
Hmmmm haven't really thought of any other good alternatives.

**Additional context**
I don't really know where the auth / token discussion ended up, so if I am misunderstanding what is needed to get persistent sessions on mobile lmk! this is just what I think will work, and I feel pretty confident that we'll need some version of an endpoint that returns the user object without providing the email + password

**Comment by gabrielsaruhashi** [comment]
@lspdrz , the solution here is to generate a never_expire token for the non-DOC user auth
for DOC user auth, we set a 5 hour expiration time or smt
